import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { APP_NAME } from './constants.js';
import { getAutostartScriptPath, type Env } from './paths.js';

/**
 * Autostart drops a tiny VBScript into the user's Startup folder. Windows runs it
 * at login and the script launches Node with a hidden window, so no console
 * flashes and nothing needs administrator rights.
 */

export function getCliScriptPath(): string {
  return fileURLToPath(new URL('../bin/warp-discord-windows.js', import.meta.url));
}

export function buildLaunchCommand(nodePath: string = process.execPath, scriptPath: string = getCliScriptPath()): string {
  return `"${nodePath}" "${scriptPath}" run --background`;
}

export function renderStartupScript(command: string): string {
  const escaped = command.replace(/"/g, '""');
  return [
    `' Generated by ${APP_NAME}. Starts Discord Rich Presence for Warp when you log in.`,
    `' Disable it with "${APP_NAME} autostart off" or simply delete this file.`,
    'Set shell = CreateObject("WScript.Shell")',
    `shell.Run "${escaped}", 0, False`,
    '',
  ].join('\r\n');
}

export interface AutostartResult {
  path: string;
  command: string;
  warnings: string[];
}

export function enableAutostart(env: Env = process.env): AutostartResult {
  const scriptPath = getCliScriptPath();
  const warnings: string[] = [];
  if (/[\\/]_npx[\\/]/i.test(scriptPath)) {
    warnings.push(
      `This copy runs from the npx cache, which gets cleaned up. Install it globally first: npm install -g ${APP_NAME}`,
    );
  }
  const command = buildLaunchCommand(process.execPath, scriptPath);
  const file = getAutostartScriptPath(env);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, renderStartupScript(command), 'utf8');
  return { path: file, command, warnings };
}

/** Returns true when a startup script was actually removed. */
export function disableAutostart(env: Env = process.env): boolean {
  const file = getAutostartScriptPath(env);
  if (!fs.existsSync(file)) return false;
  fs.rmSync(file, { force: true });
  return true;
}

export function isAutostartEnabled(env: Env = process.env): boolean {
  return fs.existsSync(getAutostartScriptPath(env));
}
