import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';

import { buildLaunchCommand, disableAutostart, enableAutostart, isAutostartEnabled, renderStartupScript } from './autostart.js';

test('buildLaunchCommand quotes both paths and runs in background mode', () => {
  assert.equal(
    buildLaunchCommand('C:\\Program Files\\nodejs\\node.exe', 'C:\\x\\bin\\warp-discord-windows.js'),
    '"C:\\Program Files\\nodejs\\node.exe" "C:\\x\\bin\\warp-discord-windows.js" run --background',
  );
});

test('renderStartupScript doubles quotes for VBScript and hides the window', () => {
  const script = renderStartupScript('"C:\\node.exe" "C:\\cli.js" run --background');
  assert.ok(script.includes('shell.Run """C:\\node.exe"" ""C:\\cli.js"" run --background", 0, False'));
  assert.ok(script.startsWith("' Generated by warp-discord-windows"));
  assert.ok(script.includes('\r\n'));
});

test('enable/disable autostart manage the Startup folder script', () => {
  const appData = fs.mkdtempSync(path.join(os.tmpdir(), 'wdw-autostart-'));
  const env = { APPDATA: appData };
  try {
    assert.equal(isAutostartEnabled(env), false);
    const result = enableAutostart(env);
    assert.ok(result.path.endsWith(path.join('Startup', 'warp-discord-windows.vbs')));
    assert.ok(fs.existsSync(result.path));
    assert.ok(fs.readFileSync(result.path, 'utf8').includes('run --background'));
    assert.equal(isAutostartEnabled(env), true);
    assert.equal(disableAutostart(env), true);
    assert.equal(disableAutostart(env), false);
    assert.equal(isAutostartEnabled(env), false);
  } finally {
    fs.rmSync(appData, { recursive: true, force: true });
  }
});
